//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_03_KhoaHoc.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class KhoaHocRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KhoaHocRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EF_03_KhoaHoc.Resources.KhoaHocRes", typeof(KhoaHocRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khoa hoc da du ngay hoc!.
        /// </summary>
        internal static string DaDuNgayHoc {
            get {
                return ResourceManager.GetString("DaDuNgayHoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sach trong!.
        /// </summary>
        internal static string DanhSachTrong {
            get {
                return ResourceManager.GetString("DanhSachTrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap dia chi: .
        /// </summary>
        internal static string DiaChi {
            get {
                return ResourceManager.GetString("DiaChi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ho ten khong duoc qua 20 ky tu!.
        /// </summary>
        internal static string ErrDoDaiHoTen {
            get {
                return ResourceManager.GetString("ErrDoDaiHoTen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoc phi phai nho hon 10 trieu!.
        /// </summary>
        internal static string ErrHocPhi {
            get {
                return ResourceManager.GetString("ErrHocPhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui long nhap theo dinh dang (yyyy/MM/dd)!.
        /// </summary>
        internal static string ErrNgaySinh {
            get {
                return ResourceManager.GetString("ErrNgaySinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So dien thoai co 10 so!.
        /// </summary>
        internal static string ErrSoDienThoai {
            get {
                return ResourceManager.GetString("ErrSoDienThoai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ho ten co it nhat 2 tu!.
        /// </summary>
        internal static string ErrSoTu {
            get {
                return ResourceManager.GetString("ErrSoTu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten khoa hoc khong duoc qua 10 ky tu!.
        /// </summary>
        internal static string ErrTenKhoaHoc {
            get {
                return ResourceManager.GetString("ErrTenKhoaHoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ghi chu: .
        /// </summary>
        internal static string GhiChu {
            get {
                return ResourceManager.GetString("GhiChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ho va ten: .
        /// </summary>
        internal static string HoTen {
            get {
                return ResourceManager.GetString("HoTen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khong tim thay hoc vien.
        /// </summary>
        internal static string KhongTimThayHocVien {
            get {
                return ResourceManager.GetString("KhongTimThayHocVien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khong tim thay khoa hoc!.
        /// </summary>
        internal static string KhongTimThayKhoaHoc {
            get {
                return ResourceManager.GetString("KhongTimThayKhoaHoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ngay sinh (nam/thang/ngay): .
        /// </summary>
        internal static string NgaySinh {
            get {
                return ResourceManager.GetString("NgaySinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap noi dung: .
        /// </summary>
        internal static string NoiDung {
            get {
                return ResourceManager.GetString("NoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap que quan: .
        /// </summary>
        internal static string QueQuan {
            get {
                return ResourceManager.GetString("QueQuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap so dien thoai: .
        /// </summary>
        internal static string SoDienThoai {
            get {
                return ResourceManager.GetString("SoDienThoai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh cong!.
        /// </summary>
        internal static string ThanhCong {
            get {
                return ResourceManager.GetString("ThanhCong", resourceCulture);
            }
        }
    }
}
